version: '3.4'



#
## EXPERIMENTAL NOT TESTED EVER
#



services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.0
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'
    restart: unless-stopped

  core:
    environment:
      - VIRTUAL_HOST=$PROD_CORE_HOST
      - VIRTUAL_PORT=13000

  grafana:
    environment:
      - VIRTUAL_HOST=$PROD_GRAFANA_HOST
      - VIRTUAL_PORT=3000
      
  blockchain-adapter:
    environment:
      - VIRTUAL_HOST=$PROD_CHAIN_ADAPTER_HOST
      - VIRTUAL_PORT=13010